/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as NutriRouteImport } from './routes/nutri'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as IndexRouteImport } from './routes/index'
import { Route as NutriIndexRouteImport } from './routes/nutri.index'
import { Route as PacienteLoginRouteImport } from './routes/paciente.login'
import { Route as NutriPacientesRouteImport } from './routes/nutri.pacientes'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const NutriRoute = NutriRouteImport.update({
  id: '/nutri',
  path: '/nutri',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const NutriIndexRoute = NutriIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => NutriRoute,
} as any)
const PacienteLoginRoute = PacienteLoginRouteImport.update({
  id: '/paciente/login',
  path: '/paciente/login',
  getParentRoute: () => rootRouteImport,
} as any)
const NutriPacientesRoute = NutriPacientesRouteImport.update({
  id: '/pacientes',
  path: '/pacientes',
  getParentRoute: () => NutriRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/nutri': typeof NutriRouteWithChildren
  '/signup': typeof SignupRoute
  '/nutri/pacientes': typeof NutriPacientesRoute
  '/paciente/login': typeof PacienteLoginRoute
  '/nutri/': typeof NutriIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/nutri/pacientes': typeof NutriPacientesRoute
  '/paciente/login': typeof PacienteLoginRoute
  '/nutri': typeof NutriIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/nutri': typeof NutriRouteWithChildren
  '/signup': typeof SignupRoute
  '/nutri/pacientes': typeof NutriPacientesRoute
  '/paciente/login': typeof PacienteLoginRoute
  '/nutri/': typeof NutriIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/nutri'
    | '/signup'
    | '/nutri/pacientes'
    | '/paciente/login'
    | '/nutri/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/signup'
    | '/nutri/pacientes'
    | '/paciente/login'
    | '/nutri'
  id:
    | '__root__'
    | '/'
    | '/forgot-password'
    | '/login'
    | '/nutri'
    | '/signup'
    | '/nutri/pacientes'
    | '/paciente/login'
    | '/nutri/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  NutriRoute: typeof NutriRouteWithChildren
  SignupRoute: typeof SignupRoute
  PacienteLoginRoute: typeof PacienteLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nutri': {
      id: '/nutri'
      path: '/nutri'
      fullPath: '/nutri'
      preLoaderRoute: typeof NutriRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nutri/': {
      id: '/nutri/'
      path: '/'
      fullPath: '/nutri/'
      preLoaderRoute: typeof NutriIndexRouteImport
      parentRoute: typeof NutriRoute
    }
    '/paciente/login': {
      id: '/paciente/login'
      path: '/paciente/login'
      fullPath: '/paciente/login'
      preLoaderRoute: typeof PacienteLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nutri/pacientes': {
      id: '/nutri/pacientes'
      path: '/pacientes'
      fullPath: '/nutri/pacientes'
      preLoaderRoute: typeof NutriPacientesRouteImport
      parentRoute: typeof NutriRoute
    }
  }
}

interface NutriRouteChildren {
  NutriPacientesRoute: typeof NutriPacientesRoute
  NutriIndexRoute: typeof NutriIndexRoute
}

const NutriRouteChildren: NutriRouteChildren = {
  NutriPacientesRoute: NutriPacientesRoute,
  NutriIndexRoute: NutriIndexRoute,
}

const NutriRouteWithChildren = NutriRoute._addFileChildren(NutriRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  NutriRoute: NutriRouteWithChildren,
  SignupRoute: SignupRoute,
  PacienteLoginRoute: PacienteLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
